// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: utils/proto/module.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ModuleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr   string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Pid    int32  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Module string `protobuf:"bytes,3,opt,name=module,proto3" json:"module,omitempty"`
}

func (x *ModuleRequest) Reset() {
	*x = ModuleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_utils_proto_module_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleRequest) ProtoMessage() {}

func (x *ModuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_utils_proto_module_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleRequest.ProtoReflect.Descriptor instead.
func (*ModuleRequest) Descriptor() ([]byte, []int) {
	return file_utils_proto_module_proto_rawDescGZIP(), []int{0}
}

func (x *ModuleRequest) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *ModuleRequest) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ModuleRequest) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

type ModuleReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ModuleReply) Reset() {
	*x = ModuleReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_utils_proto_module_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModuleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleReply) ProtoMessage() {}

func (x *ModuleReply) ProtoReflect() protoreflect.Message {
	mi := &file_utils_proto_module_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleReply.ProtoReflect.Descriptor instead.
func (*ModuleReply) Descriptor() ([]byte, []int) {
	return file_utils_proto_module_proto_rawDescGZIP(), []int{1}
}

func (x *ModuleReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_utils_proto_module_proto protoreflect.FileDescriptor

var file_utils_proto_module_proto_rawDesc = []byte{
	0x0a, 0x18, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x6f,
	0x64, 0x75, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x16, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62,
	0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4d, 0x0a, 0x0d, 0x4d, 0x6f, 0x64,
	0x75, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64,
	0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x12, 0x10,
	0x0a, 0x03, 0x70, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x70, 0x69, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x22, 0x27, 0x0a, 0x0b, 0x4d, 0x6f, 0x64, 0x75,
	0x6c, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x32, 0x70, 0x0a, 0x06, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x32, 0x0a, 0x04, 0x53,
	0x65, 0x6e, 0x64, 0x12, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x6f, 0x64, 0x75,
	0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12,
	0x32, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x00, 0x42, 0x51, 0x0a, 0x17, 0x69, 0x6f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x05,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x7a, 0x68, 0x61, 0x6e, 0x67, 0x73, 0x68, 0x61, 0x6e, 0x77, 0x65, 0x6e,
	0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2f, 0x75, 0x74, 0x69, 0x6c, 0x73,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_utils_proto_module_proto_rawDescOnce sync.Once
	file_utils_proto_module_proto_rawDescData = file_utils_proto_module_proto_rawDesc
)

func file_utils_proto_module_proto_rawDescGZIP() []byte {
	file_utils_proto_module_proto_rawDescOnce.Do(func() {
		file_utils_proto_module_proto_rawDescData = protoimpl.X.CompressGZIP(file_utils_proto_module_proto_rawDescData)
	})
	return file_utils_proto_module_proto_rawDescData
}

var file_utils_proto_module_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_utils_proto_module_proto_goTypes = []interface{}{
	(*ModuleRequest)(nil), // 0: proto.ModuleRequest
	(*ModuleReply)(nil),   // 1: proto.ModuleReply
	(*NormalRequest)(nil), // 2: proto.NormalRequest
	(*NormalReply)(nil),   // 3: proto.NormalReply
}
var file_utils_proto_module_proto_depIdxs = []int32{
	0, // 0: proto.Module.Send:input_type -> proto.ModuleRequest
	2, // 1: proto.Module.Ping:input_type -> proto.NormalRequest
	1, // 2: proto.Module.Send:output_type -> proto.ModuleReply
	3, // 3: proto.Module.Ping:output_type -> proto.NormalReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_utils_proto_module_proto_init() }
func file_utils_proto_module_proto_init() {
	if File_utils_proto_module_proto != nil {
		return
	}
	file_utils_proto_base_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_utils_proto_module_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModuleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_utils_proto_module_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModuleReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_utils_proto_module_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_utils_proto_module_proto_goTypes,
		DependencyIndexes: file_utils_proto_module_proto_depIdxs,
		MessageInfos:      file_utils_proto_module_proto_msgTypes,
	}.Build()
	File_utils_proto_module_proto = out.File
	file_utils_proto_module_proto_rawDesc = nil
	file_utils_proto_module_proto_goTypes = nil
	file_utils_proto_module_proto_depIdxs = nil
}
